from __future__ import annotations

import csv
from dataclasses import dataclass
from pathlib import Path

import numpy as np


def wrap_angle(values: np.ndarray) -> np.ndarray:
    """Wrap angles to ``[-pi, pi)`` while preserving shape."""

    array = np.asarray(values, dtype=np.float64)
    return (array + np.pi) % (2.0 * np.pi) - np.pi


@dataclass(frozen=True)
class KickHarmonic:
    """One Fourier kick ``epsilon sin(m theta + phase)``."""

    order: int
    amplitude: float
    phase: float = 0.0

    def __post_init__(self) -> None:
        if self.order < 1:
            raise ValueError("kick order must be positive")
        if not np.isfinite((self.amplitude, self.phase)).all():
            raise ValueError("kick parameters must be finite")

    @property
    def generating_amplitude(self) -> float:
        return abs(self.amplitude) / self.order


@dataclass(frozen=True)
class TwistKickMap:
    """Exact-symplectic kick followed by an action-dependent rotation."""

    base_frequency: float
    twist: float
    kicks: tuple[KickHarmonic, ...]

    def __post_init__(self) -> None:
        if not np.isfinite((self.base_frequency, self.twist)).all():
            raise ValueError("map parameters must be finite")
        if self.twist == 0.0:
            raise ValueError("twist must be nonzero")

    def step(
        self,
        action: np.ndarray,
        angle: np.ndarray,
    ) -> tuple[np.ndarray, np.ndarray]:
        action_array = np.asarray(action, dtype=np.float64)
        angle_array = np.asarray(angle, dtype=np.float64)
        if action_array.shape != angle_array.shape:
            raise ValueError("action and angle must have matching shapes")
        updated_action = action_array.copy()
        for kick in self.kicks:
            updated_action += kick.amplitude * np.sin(
                kick.order * angle_array + kick.phase
            )
        updated_angle = wrap_angle(
            angle_array + self.base_frequency + self.twist * updated_action
        )
        return updated_action, updated_angle

    def frequency(self, action: np.ndarray | float) -> np.ndarray:
        return self.base_frequency + self.twist * np.asarray(
            action,
            dtype=np.float64,
        )

    def resonance_action(self, order: int, *, resonance_index: int = 1) -> float:
        if order < 1 or resonance_index < 1:
            raise ValueError("resonance order and index must be positive")
        return (
            2.0 * np.pi * resonance_index / order - self.base_frequency
        ) / self.twist

    def island_half_width(self, order: int) -> float:
        """Leading pendulum halfwidth using the generating amplitude."""

        matching = [kick for kick in self.kicks if kick.order == order]
        if len(matching) != 1:
            raise ValueError(f"expected exactly one kick at order {order}")
        return 2.0 * np.sqrt(
            matching[0].generating_amplitude / abs(self.twist)
        )


@dataclass(frozen=True)
class ExactGauge:
    """Exact canonical map generated by ``S=theta*J+g*J*sin(k*theta+chi)``."""

    amplitude: float
    order: int
    phase: float = 0.0

    def __post_init__(self) -> None:
        if self.order < 1:
            raise ValueError("gauge order must be positive")
        if not np.isfinite((self.amplitude, self.phase)).all():
            raise ValueError("gauge parameters must be finite")
        if abs(self.amplitude * self.order) >= 0.8:
            raise ValueError("gauge requires |amplitude * order| < 0.8")

    @property
    def peak_action_fraction(self) -> float:
        return abs(self.amplitude * self.order)

    def forward(
        self,
        action: np.ndarray,
        angle: np.ndarray,
    ) -> tuple[np.ndarray, np.ndarray]:
        action_array = np.asarray(action, dtype=np.float64)
        angle_array = np.asarray(angle, dtype=np.float64)
        denominator = 1.0 + self.amplitude * self.order * np.cos(
            self.order * angle_array + self.phase
        )
        transformed_action = action_array / denominator
        transformed_angle = wrap_angle(
            angle_array
            + self.amplitude
            * np.sin(self.order * angle_array + self.phase)
        )
        return transformed_action, transformed_angle

    def inverse(
        self,
        transformed_action: np.ndarray,
        transformed_angle: np.ndarray,
    ) -> tuple[np.ndarray, np.ndarray]:
        target_angle = np.asarray(transformed_angle, dtype=np.float64)
        angle = target_angle.copy()
        for _ in range(16):
            argument = self.order * angle + self.phase
            residual = (
                angle + self.amplitude * np.sin(argument) - target_angle
            )
            derivative = 1.0 + self.amplitude * self.order * np.cos(argument)
            angle -= residual / derivative
        denominator = 1.0 + self.amplitude * self.order * np.cos(
            self.order * angle + self.phase
        )
        action = np.asarray(transformed_action, dtype=np.float64) * denominator
        return action, wrap_angle(angle)


@dataclass(frozen=True)
class ObservationChart:
    """Known nontrivial canonical observation chart for reference experiments."""

    action_shears: tuple[tuple[int, float, float], ...] = (
        (1, 0.24, 0.35),
        (2, 0.10, -0.20),
    )
    angle_offset: float = 0.4
    angle_twist: float = 0.12
    linear_q_q: float = 1.12
    linear_q_p: float = 0.18
    linear_p_q: float = 0.12

    def __post_init__(self) -> None:
        if any(order < 1 for order, _, _ in self.action_shears):
            raise ValueError("observation harmonics must be positive")
        if not np.isfinite(
            (
                self.angle_offset,
                self.angle_twist,
                self.linear_q_q,
                self.linear_q_p,
                self.linear_p_q,
            )
        ).all():
            raise ValueError("observation-chart parameters must be finite")
        if abs(self.linear_q_q) < 1e-12:
            raise ValueError("linear_q_q must be nonzero")

    @property
    def linear_p_p(self) -> float:
        return (
            1.0 + self.linear_q_p * self.linear_p_q
        ) / self.linear_q_q

    @property
    def matrix(self) -> np.ndarray:
        return np.asarray(
            (
                (self.linear_q_q, self.linear_q_p),
                (self.linear_p_q, self.linear_p_p),
            ),
            dtype=np.float64,
        )

    def observe(
        self,
        action: np.ndarray,
        angle: np.ndarray,
    ) -> np.ndarray:
        action_array = np.asarray(action, dtype=np.float64)
        original_angle = np.asarray(angle, dtype=np.float64)
        observed_action = action_array.copy()
        for order, amplitude, phase in self.action_shears:
            observed_action += amplitude * np.cos(
                order * original_angle + phase
            )
        if np.any(observed_action <= 0.0):
            raise ValueError("observation chart produced nonpositive action")
        observed_angle = wrap_angle(
            original_angle
            + self.angle_offset
            + self.angle_twist * observed_action
        )
        radius = np.sqrt(2.0 * observed_action)
        canonical = np.stack(
            (
                radius * np.cos(observed_angle),
                -radius * np.sin(observed_angle),
            ),
            axis=-1,
        )
        return canonical @ self.matrix.T

    def unobserve(self, states: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
        values = np.asarray(states, dtype=np.float64)
        if values.ndim == 0 or values.shape[-1] != 2:
            raise ValueError("expected states with final dimension two")
        canonical = values @ np.linalg.inv(self.matrix).T
        q, p = canonical[..., 0], canonical[..., 1]
        observed_action = 0.5 * (q * q + p * p)
        observed_angle = np.arctan2(-p, q)
        angle = wrap_angle(
            observed_angle
            - self.angle_offset
            - self.angle_twist * observed_action
        )
        action = observed_action.copy()
        for order, amplitude, phase in self.action_shears:
            action -= amplitude * np.cos(order * angle + phase)
        return action, angle


@dataclass(frozen=True)
class MapTrajectoryBundle:
    """Observed states and oracle coordinates from one deterministic fixture."""

    states: np.ndarray
    actions: np.ndarray
    angles: np.ndarray
    trajectory_ids: tuple[str, ...]


def simulate_map_trajectories(
    system: TwistKickMap,
    chart: ObservationChart,
    *,
    initial_actions: np.ndarray,
    initial_angles: np.ndarray,
    steps: int,
) -> MapTrajectoryBundle:
    actions0 = np.asarray(initial_actions, dtype=np.float64)
    angles0 = np.asarray(initial_angles, dtype=np.float64)
    if actions0.ndim != 1 or actions0.shape != angles0.shape:
        raise ValueError("initial actions and angles must be matching vectors")
    if steps < 3:
        raise ValueError("map trajectories need at least three states")
    actions = np.empty((len(actions0), steps), dtype=np.float64)
    angles = np.empty_like(actions)
    actions[:, 0] = actions0
    angles[:, 0] = wrap_angle(angles0)
    for step in range(1, steps):
        actions[:, step], angles[:, step] = system.step(
            actions[:, step - 1],
            angles[:, step - 1],
        )
    states = chart.observe(actions, angles)
    return MapTrajectoryBundle(
        states=states,
        actions=actions,
        angles=angles,
        trajectory_ids=tuple(
            f"map-run-{index:03d}" for index in range(len(actions0))
        ),
    )


def write_map_trajectory_csv(path: Path, bundle: MapTrajectoryBundle) -> Path:
    """Write observed states plus explicit oracle columns for reference runs."""

    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.writer(handle, lineterminator="\n")
        writer.writerow(
            (
                "trajectory_id",
                "time",
                "position",
                "momentum",
                "oracle_action",
                "oracle_angle",
            )
        )
        for trajectory, trajectory_id in enumerate(bundle.trajectory_ids):
            for step in range(bundle.states.shape[1]):
                writer.writerow(
                    (
                        trajectory_id,
                        step,
                        f"{bundle.states[trajectory, step, 0]:.17g}",
                        f"{bundle.states[trajectory, step, 1]:.17g}",
                        f"{bundle.actions[trajectory, step]:.17g}",
                        f"{bundle.angles[trajectory, step]:.17g}",
                    )
                )
    return path
